### ISSUE TITLE
Can not access via 3D Touch menu

### ISSUE THREAD

**Issue by inomfood** [FouadRaheb/AppData#1]
With update 1.1, my iPhone XS Max on iOS 12.1.1b3 is no longer able to access AppData through 3D Touch. There is an option in the 3D Touch menu, but tapping it does nothing. However, the sliding option works to access it. 

I have downgraded to 1.0 and confirmed that the 3D Touch options works as intended in this version. However, upon updating to 1.1, the issue arises again.

**Comment by haoict** [comment]
Same here. 1.0 works well with 3D touch but 1.1 doesn't
iOS 12.4, iPhone 7

**Comment by FouadRaheb** [comment]
Already fixed in my upcoming update, still has some stuff to add before releasing it
